"""Generate a commented ``extra.toml`` starter from a board.

Not a provider: this reads an extract and writes a file a human then edits. The
point is to remove the blank-page problem — the blocks that are obvious from the
board alone (mechanical parts that must not move, dissipating parts that need a
power figure, the decoupling heuristic already at work) are written out with the
board's real reference designators and counts, and everything uncertain is left
commented so the file is safe to use as-is.
"""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from .providers.parts_file import MPN_FIELDS, SUPPLIER_FIELDS, field_value

#: Reference prefixes treated as mechanical: they are placed by the designer and
#: must not move.
MECHANICAL_PREFIXES = ("H", "FID", "J", "MK", "TP")

#: Reference prefixes likely to dissipate, in the order they are suggested.
THERMAL_PREFIXES = ("U", "Q", "L", "CE", "D")

#: Human labels for the suggestions, when the prefix is a known convention.
PREFIX_LABELS = {
    "H": "mounting holes",
    "FID": "fiducials",
    "J": "connectors",
    "MK": "mounting hardware",
    "TP": "test points",
    "U": "ICs",
    "Q": "transistors",
    "L": "inductors",
    "CE": "electrolytic capacitors",
    "D": "diodes and LEDs",
}

_REF_PREFIX = re.compile(r"^([A-Za-z]+)")


@dataclass
class BoardHints:
    """What can be read off the board to seed the rules file."""

    board_name: str
    by_prefix: dict[str, list[str]] = field(default_factory=dict)
    pins_by_ref: dict[str, int] = field(default_factory=dict)
    value_by_ref: dict[str, str] = field(default_factory=dict)
    netclasses: list[str] = field(default_factory=list)
    diff_pair_count: int = 0

    def refs(self, prefix: str) -> list[str]:
        return sorted(self.by_prefix.get(prefix, []), key=_natural_key)

    def count(self, prefix: str) -> int:
        return len(self.by_prefix.get(prefix, []))


def _natural_key(ref: str):
    """Sort D2 before D10."""
    match = re.match(r"^([A-Za-z]+)(\d*)", ref)
    if not match:
        return (ref, 0)
    return (match.group(1), int(match.group(2) or 0))


def hints_from_extract(doc: dict) -> BoardHints:
    board_path = doc.get("board", {}).get("path", "")
    hints = BoardHints(board_name=Path(board_path).name if board_path else "board.kicad_pcb")

    by_prefix: dict[str, list[str]] = defaultdict(list)
    for component in doc.get("components", []):
        match = _REF_PREFIX.match(str(component.get("ref", "")))
        if not match:
            continue
        prefix = match.group(1).upper()
        by_prefix[prefix].append(str(component["ref"]))
        hints.pins_by_ref[str(component["ref"])] = len(component.get("pads", []))
        hints.value_by_ref[str(component["ref"])] = str(component.get("value", ""))
    hints.by_prefix = dict(by_prefix)
    hints.netclasses = sorted({nc["name"] for nc in doc.get("netclasses", [])})
    hints.diff_pair_count = sum(
        1
        for name in {pad.get("net") for c in doc.get("components", []) for pad in c.get("pads", [])}
        if name and name.lower().endswith(("_p", "-p", "+"))
    )
    return hints


def _plural(count: int, label: str) -> str:
    """`1 connector`, `3 connectors`."""
    if count == 1 and label.endswith("s"):
        return label[:-1]
    return label


def _sample_refs(hints: BoardHints, prefix: str, limit: int) -> list[str]:
    refs = hints.refs(prefix)
    if prefix == "U" and refs:
        # The biggest package is the interesting one for a thermal envelope.
        refs = sorted(refs, key=lambda ref: (-hints.pins_by_ref.get(ref, 0), _natural_key(ref)))
    return refs[:limit]


def render_template(hints: BoardHints, *, generated_by: str = "dodplace enrich extra") -> str:
    """A commented rules file seeded with this board's parts."""
    lines: list[str] = []
    add = lines.append

    add(f"# dodplace user rules for {hints.board_name}")
    add("#")
    add(f"# Generated by `{generated_by}` as a starting point, not as a result:")
    add("# the blocks below are seeded with this board's real parts, and every key")
    add("# you leave out keeps its documented fallback.")
    add("#")
    add("# Auto-discovered next to the board as `extra.toml` or `dodplace.toml`.")
    add("# Selectors accept globs (`ref = \"FID*\"`, `fpid = \"Tuile_LED:*\"`); later")
    add("# blocks win field by field, so put a family rule first and refinements after.")
    add("# Anything left unresolved shows up in the enrichment report and in the")
    add("# `unresolved:` line the plugin prints.")
    add("")
    add("[board]")
    add("# No part taller than this above the board surface (mm); 0 = no z test.")
    add("# ceiling_height_mm = 25.0")
    add("# Airflow direction; [0, 0] means isotropic dissipation.")
    add("# airflow = [1.0, 0.0]")
    add("# false forbids vias under component courtyards.")
    add("# via_under_body_allowed = false")
    add("# Margin used when a courtyard has to be derived from pad extents (mm).")
    add("# courtyard_fallback_margin = 0.25")
    add("")

    if hints.netclasses:
        add("# Net classes already come from the board:")
        add("#   " + ", ".join(hints.netclasses))
        add("# Give a single net its own clearance, or override a whole class:")
        add("# [board.net_clearance]")
        add('# "VCC" = 0.4')
        if len(hints.netclasses) > 1:
            add("# [board.class_clearance]")
            add(f"# {hints.netclasses[-1]} = 0.4")
        add("")

    mechanical = [(prefix, hints.count(prefix)) for prefix in MECHANICAL_PREFIXES
                  if hints.count(prefix)]
    if mechanical:
        add("# " + "-" * 72)
        add("# Mechanical parts: these must not move.")
        for prefix, count in mechanical:
            label = PREFIX_LABELS.get(prefix, prefix)
            sample = ", ".join(hints.refs(prefix)[:4])
            add(f"# {count} {_plural(count, label)}: {sample}{' …' if count > 4 else ''}")
        add("# " + "-" * 72)
        for prefix, _count in mechanical:
            label = PREFIX_LABELS.get(prefix, prefix)
            add("[[component]]")
            add(f'ref = "{prefix}*"'.ljust(24) + f"# {label}")
            add("locked = true")
            if prefix == "J":
                add("rot_fixed = true")
            add("")
    else:
        add("# No mechanical part was recognised (mounting holes, fiducials,")
        add("# connectors). Lock them here if they must not move:")
        add("# [[component]]")
        add('# ref = "J*"')
        add("# locked = true")
        add("")

    thermal = [(prefix, hints.count(prefix)) for prefix in THERMAL_PREFIXES
               if hints.count(prefix)]
    if thermal:
        add("# " + "-" * 72)
        add("# Dissipating parts. A non-zero power_w becomes a thermal constraint")
        add("# automatically; add r_theta_ja and an exclusion radius if you know them.")
        add("#")
        add("# " + ", ".join(f"{count} {_plural(count, PREFIX_LABELS.get(prefix, prefix))}"
                            for prefix, count in thermal))
        add("# " + "-" * 72)
        suggested = 0
        for prefix, _count in thermal:
            for ref in _sample_refs(hints, prefix, 1):
                value = hints.value_by_ref.get(ref, "")
                add("[[component]]")
                add(f'ref = "{ref}"'.ljust(24) + (f"# {value}" if value else ""))
                add("# power_w = 0.2")
                add("# r_theta_ja = 45.0")
                add("# exclusion_radius_mm = 3.0")
                add("")
                suggested += 1
            if suggested >= 3:
                break
        add("# ... and the rest by reference, for instance:")
        add("# [[thermal]]")
        add("# component = \"U1\"")
        add("# power_w = 0.3")
        add("# radius_mm = 3.0")
        add("")

    add("# " + "-" * 72)
    add("# Decoupling. The netlist heuristic already pairs capacitors with the ICs")
    add("# that share their power net. Adding any [[decoupling]] row REPLACES the")
    add("# heuristic entirely, so only add rows to override it.")
    add("# " + "-" * 72)
    add("# [[decoupling]]")
    add('# ic = "U1"')
    add('# cap = "C1"')
    add('# pin = "1"')
    add("# max_distance_mm = 4.0")
    add("")

    led_like = [prefix for prefix in ("D",) if hints.count(prefix) > 1]
    if led_like:
        refs = hints.refs("D")
        add("# " + "-" * 72)
        add(f"# Symmetry. {hints.count('D')} diodes/LEDs are on this board; if two of")
        add("# them must stay mirrored, declare it here.")
        add("# " + "-" * 72)
        add("# [[symmetry]]")
        add(f'# a = "{refs[0]}"')
        add(f'# b = "{refs[1]}"')
        add('# axis = "x"        # x, y or fixed')
        add("")

    add("# " + "-" * 72)
    add("# Forbidden areas, in board coordinates (mm). layer_mask is a copper layer")
    add("# bitmask; 0 means every layer.")
    add("# " + "-" * 72)
    add("# [[keepout]]")
    add("# layer_mask = 3")
    add("# polygon = [[40, 2], [48, 2], [48, 8], [40, 8]]")
    add("")
    return "\n".join(lines)


def write_template(
    doc: dict,
    output: str | Path,
    *,
    force: bool = False,
    generated_by: str = "dodplace enrich extra",
) -> Path:
    """Write the starter file; refuses to clobber an existing one."""
    path = Path(output)
    if path.exists() and not force:
        raise FileExistsError(
            f"{path} already exists; edit it, or pass --force to replace it"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_template(hints_from_extract(doc), generated_by=generated_by))
    return path


# ---------------------------------------------------------------------------
# Parts-file skeleton
# ---------------------------------------------------------------------------

#: Header of the generated CSV. Every column is understood by
#: `dodplace enrich parts`, so the file can be re-imported untouched.
SKELETON_COLUMNS = (
    "LCSC Part #",
    "MPN",
    "Footprint",
    "Comment",
    "Designator",
    "Height (mm)",
    "Mass (g)",
    "Power (W)",
    "Datasheet",
)




@dataclass
class SkeletonRow:
    """One line item: a supplier code and the board parts it covers."""

    code: str
    refs: list[str]
    footprint: str = ""
    value: str = ""
    mpn: str = ""

    def designators(self) -> str:
        listed = " ".join(self.refs[:3])
        suffix = " …" if len(self.refs) > 3 else ""
        return f"{len(self.refs)}x {listed}{suffix}"


def supplier_code(component: dict) -> str:
    return field_value(component, SUPPLIER_FIELDS)


def skeleton_rows(doc: dict) -> list[SkeletonRow]:
    """Group the board's parts by supplier code, ready to be filled in.

    Only supplier-coded parts get a row: a parts file is matched by LCSC code,
    MPN or footprint, and a code is the only identity that can carry real
    dimensions. One row per code, not per component.
    """
    grouped: dict[str, list[dict]] = defaultdict(list)
    for component in doc.get("components", []):
        code = supplier_code(component)
        if code:
            grouped[code].append(component)

    rows = []
    for code in sorted(grouped):
        components = grouped[code]
        footprints = Counter(c.get("fpid", "") for c in components)
        values = Counter(str(c.get("value", "")) for c in components if c.get("value"))
        mpn = next((field_value(c, MPN_FIELDS) for c in components
                    if field_value(c, MPN_FIELDS)), "")
        rows.append(
            SkeletonRow(
                code=code,
                refs=sorted((str(c["ref"]) for c in components), key=_natural_key),
                footprint=footprints.most_common(1)[0][0] if footprints else "",
                value=values.most_common(1)[0][0] if values else "",
                mpn=mpn,
            )
        )
    return rows


def render_skeleton(rows: list[SkeletonRow], *, generated_by: str = "dodplace enrich skeleton"
                    ) -> str:
    """The CSV text: identity columns filled, the four data columns empty."""
    import csv
    import io

    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(SKELETON_COLUMNS)
    for row in rows:
        writer.writerow([
            row.code,
            row.mpn,
            row.footprint,
            row.value,
            row.designators(),
            "",  # Height (mm)
            "",  # Mass (g)
            "",  # Power (W)
            "",  # Datasheet
        ])
    header = (
        f"# {generated_by}: pre-filled from the board, to be completed by hand.\n"
        f"# Every column is understood by `dodplace enrich parts`, so this file can\n"
        f"# be re-imported as-is once filled in.\n"
    )
    return header + buffer.getvalue()


def summary(doc: dict) -> Counter:
    """Counts by prefix, for the console message."""
    hints = hints_from_extract(doc)
    return Counter({prefix: len(refs) for prefix, refs in hints.by_prefix.items()})
